package io.github.dgavrikov.core.outbox.model;

import lombok.Builder;

import java.util.Map;

/**
 * An immutable domain record representing a captured outbox event log entry.
 * This object serves as the unified data carrier across the database layer,
 * the in-memory streaming pipeline, and the transport publishing plugins.
 */
@Builder
public record OutboxEvent(
        /** Unique global sequence identifier generated by the database. */
        Long id,

        /**Metadata descriptor type determining which plugin routes this event. */
        OutboxEventType eventType,

        /**
         * The business partition key identifier (e.g., Kafka Record Key / REST routing ID).
         * Replaces the legacy aggregateId to detach outbox logic from specific entity lifecycles.
         */
        String keyId,

        /** The pre-serialized event body, stored as a raw JSON/JSONB string. */
        String payload,

        /**
         * A thread-safe, immutable flat map of transport metadata headers
         * used for distributed tracing (e.g., W3C traceparent, tenantId).
         */
        Map<String, String> headers

) {
}
